enum_from_primitive! {
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub enum GameTag {
        TagScriptDataNum1 = 2,
        // TAG_SCRIPT_DATA_NUM_2 = 3
        // TAG_SCRIPT_DATA_ENT_1 = 4
        // TAG_SCRIPT_DATA_ENT_2 = 5
        // MISSION_EVENT = 6
        // TIMEOUT = 7
        // TURN_START = 8
        // TURN_TIMER_SLUSH = 9
        // PREMIUM = 12
        // GOLD_REWARD_STATE = 13
        // PLAYSTATE = 17
        // LAST_AFFECTED_BY = 18
        // STEP = 19
        // TURN = 20
        // FATIGUE = 22
        // CURRENT_PLAYER = 23
        // FIRST_PLAYER = 24
        // RESOURCES_USED = 25
        // RESOURCES = 26
        // HERO_ENTITY = 27
        // MAXHANDSIZE = 28
        // STARTHANDSIZE = 29
        // PLAYER_ID = 30
        // TEAM_ID = 31
        TriggerVisual = 32,
        // RECENTLY_ARRIVED = 33
        // PROTECTED = 34
        // PROTECTING = 35
        // DEFENDING = 36
        // PROPOSED_DEFENDER = 37
        // ATTACKING = 38
        // PROPOSED_ATTACKER = 39
        // ATTACHED = 40
        // EXHAUSTED = 43
        // DAMAGE = 44
        Health = 45,
        Atk = 47,
        Cost = 48,
        // ZONE = 49
        // CONTROLLER = 50
        // OWNER = 51
        // DEFINITION = 52
        // ENTITY_ID = 53
        // HISTORY_PROXY = 54
        // COPY_DEATHRATTLE = 55
        Elite = 114,
        // MAXRESOURCES = 176
        CardSet = 183,
        Durability = 187,
        // SILENCED = 188
        WindFury = 189,
        Taunt = 190,
        Stealth = 191,
        SpellPower = 192,
        DivineShield = 194,
        Charge = 197,
        // NEXT_STEP = 198
        Class = 199,
        CardRace = 200,
        Faction = 201,
        CardType = 202,
        Rarity = 203,
        // STATE = 204
        Summoned = 205,
        Freeze = 208,
        Enraged = 212,
        Overload = 215,
        // LOYALTY = 216
        // BATTLECRY = 218
        Deathrattle = 217,
        Battlecry = 218,
        Secret = 219,
        Combo = 220,
        // CANT_HEAL = 221
        // CANT_DAMAGE = 222
        // CANT_SET_ASIDE = 223
        // CANT_REMOVE_FROM_GAME = 224
        // CANT_READY = 225
        // CANT_ATTACK = 227
        CantAttack = 227,
        // CANT_DISCARD = 230
        // CANT_PLAY = 231
        // CANT_DRAW = 232
        // CANT_BE_HEALED = 239
        Immune = 240,
        // CANT_BE_SET_ASIDE = 241
        // CANT_BE_REMOVED_FROM_GAME = 242
        // CANT_BE_READIED = 243
        // CANT_BE_ATTACKED = 245
        // CANT_BE_TARGETED = 246
        // CANT_BE_DESTROYED = 247
        AttackVisualType = 251,
        // CANT_BE_SUMMONING_SICK = 253
        // FROZEN = 260
        // JUST_PLAYED = 261
        // LINKED_ENTITY = 262
        // ZONE_POSITION = 263
        // CANT_BE_FROZEN = 264
        // COMBO_ACTIVE = 266
        // CARD_TARGET = 267
        DevState = 268,
        // NUM_CARDS_PLAYED_THIS_TURN = 269
        // CANT_BE_TARGETED_BY_OPPONENTS = 270
        // NUM_TURNS_IN_PLAY = 271
        // NUM_TURNS_LEFT = 272
        // CURRENT_SPELLPOWER = 291
        // ARMOR = 292
        Morph = 293,
        // IS_MORPHED = 294
        // TEMP_RESOURCES = 295
        OverloadOwed = 296,
        // NUM_ATTACKS_THIS_TURN = 297
        // NEXT_ALLY_BUFF = 302
        // MAGNET = 303
        // FIRST_CARD_PLAYED_THIS_TURN = 304
        // MULLIGAN_STATE = 305
        // TAUNT_READY = 306
        // STEALTH_READY = 307
        // CHARGE_READY = 308
        CantBeTargetedBySpells = 311,
        // SHOULDEXITCOMBAT = 312
        // CREATOR = 313
        // CANT_BE_SILENCED = 314
        // PARENT_CARD = 316
        // NUM_MINIONS_PLAYED_THIS_TURN = 317
        // PREDAMAGE = 318
        Collectible = 321,
        EnchantmentBirthVisual = 330,
        EnchantmentIdleVisual = 331,
        CantBeTargetedByHeroPowers = 332,
        InvisibleDeathrattle = 335,
        // HEALTH_MINIMUM = 337
        TagOneTurnEffect = 338,
        Silence = 339,
        Counter = 340,
        // HAND_REVEALED = 348
        ImmuneToSpellPower = 349,
        AdjacentBuff = 350,
        // FORCED_PLAY = 352
        // LOW_HEALTH_THRESHOLD = 353
        // SPELLPOWER_DOUBLE = 356
        // HEALING_DOUBLE = 357
        // NUM_OPTIONS_PLAYED_THIS_TURN = 358
        // TO_BE_DESTROYED = 360
        Aura = 362,
        Poisonous = 363,
        // HERO_POWER_DOUBLE = 366
        AiMustPlay = 367,
        // NUM_MINIONS_PLAYER_KILLED_THIS_TURN = 368
        // NUM_MINIONS_KILLED_THIS_TURN = 369
        AffectedBySpellPower = 370,
        // EXTRA_DEATHRATTLES = 371
        // START_WITH_1_HEALTH = 372
        // IMMUNE_WHILE_ATTACKING = 373
        // MULTIPLY_HERO_DAMAGE = 374
        // MULTIPLY_BUFF_VALUE = 375
        // CUSTOM_KEYWORD_EFFECT = 376
        TopDeck = 377,
        // CANT_BE_TARGETED_BY_BATTLECRIES = 379
        HeroPower = 380,
        // DEATHRATTLE_RETURN_ZONE = 382
        // STEADY_SHOT_CAN_TARGET = 383
        // DISPLAYED_CREATOR = 385
        // POWERED_UP = 386
        SparePart = 388,
        Forgetful = 389,
        // CAN_SUMMON_MAXPLUSONE_MINION = 390
        // OBFUSCATED = 391
        // BURNING = 392
        // OVERLOAD_LOCKED = 393
        // NUM_TIMES_HERO_POWER_USED_THIS_GAME = 394
        // CURRENT_HEROPOWER_DAMAGE_BONUS = 395
        HeroPowerDamage = 396,
        // LAST_CARD_PLAYED = 397
        // NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_TURN = 398
        // NUM_CARDS_DRAWN_THIS_TURN = 399
        // AI_ONE_SHOT_KILL = 400
        EvilGlow = 401,
        HideStats = 402,
        Inspire = 403,
        ReceivesDoubleSpellDamageBonus = 404,
        // HEROPOWER_ADDITIONAL_ACTIVATIONS = 405
        // HEROPOWER_ACTIVATIONS_THIS_TURN = 406
        // REVEALED = 410
        // NUM_FRIENDLY_MINIONS_THAT_DIED_THIS_GAME = 412
        // CANNOT_ATTACK_HEROES = 413
        // LOCK_AND_LOAD = 414
        Discover = 415,
        // SHADOWFORM = 416
        // NUM_FRIENDLY_MINIONS_THAT_ATTACKED_THIS_TURN = 417
        // NUM_RESOURCES_SPENT_THIS_GAME = 418
        // CHOOSE_BOTH = 419
        // ELECTRIC_CHARGE_LEVEL = 420
        // HEAVILY_ARMORED = 421
        // DONT_SHOW_IMMUNE = 422
        // RITUAL = 424
        Ritual = 424,
        // PREHEALING = 425
        AppearFunctionallyDead = 426,
        // OVERLOAD_THIS_GAME = 427
        // SPELLS_COST_HEALTH = 431
        // HISTORY_PROXY_NO_BIG_CARD = 432
        // PROXY_CTHUN = 434
        // TRANSFORMED_FROM_CARD = 435
        // CTHUN = 436
        // CAST_RANDOM_SPELLS = 437
        // SHIFTING = 438
        JadeGolem = 441,
        // EMBRACE_THE_SHADOW = 442
        // CHOOSE_ONE = 443
        ChooseOne = 443,
        // EXTRA_ATTACKS_THIS_TURN = 444
        // SEEN_CTHUN = 445
        // MINION_TYPE_REFERENCE = 447
        Untouchable = 448,
        // RED_MANA_CRYSTALS = 449
        // SCORE_LABELID_1 = 450
        // SCORE_VALUE_1 = 451
        // SCORE_LABELID_2 = 452
        // SCORE_LABELID_3 = 454
        // SCORE_VALUE_2 = 453
        // SCORE_VALUE_3 = 455
        CantBeFatigued = 456,
        AutoAttack = 457,
        // ARMS_DEALING = 458
        // TAG_LAST_KNOWN_COST_IN_HAND = 466
        // DEFINING_ENCHANTMENT = 469
        FinishAttackSpellOnDamage = 470,
        // KAZAKUS_POTION_POWER_1 = 471
        // KAZAKUS_POTION_POWER_2 = 472
        // MODIFY_DEFINITION_ATTACK = 473
        // MODIFY_DEFINITION_HEALTH = 474
        // MODIFY_DEFINITION_COST = 475
        // MULTIPLE_CLASSES = 476
        MultipleClasses = 476,
        // ALL_TARGETS_RANDOM = 477
        MultiClassGroup = 480,
        // CARD_COSTS_HEALTH = 481
        GrimyGoons = 482,
        JadeLotus = 483,
        Kabal = 484,
        // ADDITIONAL_PLAY_REQS_1 = 515
        // ADDITIONAL_PLAY_REQS_2 = 516

        // GrantCharge = 355
        // HealTarget = 361

        // # strings (all deleted?)
        CardTextInHand = 184,
        CardName = 185,
        ArtistName = 342,
        FlavorText = 351,
        HowToEarn = 364,
        HowToEarnGolden = 365,
        // CardTextInPlay = 252
        TargetingArrowText = 325,
        // LocalizationNotes = 344

        // # Renamed
        // CANT_BE_DAMAGED = IMMUNE
        // CANT_BE_DISPELLED = CANT_BE_SILENCED
        // CANT_BE_TARGETED_BY_ABILITIES = CANT_BE_TARGETED_BY_SPELLS
        // DEATH_RATTLE = DEATHRATTLE
        // DEATHRATTLE_SENDS_BACK_TO_DECK = DEATHRATTLE_RETURN_ZONE
        // HIDE_COST = HIDE_STATS
        // LINKEDCARD = LINKED_ENTITY
        // RECALL = OVERLOAD
        // RECALL_OWED = OVERLOAD_OWED
        // TAG_HERO_POWER_DOUBLE = HERO_POWER_DOUBLE
        // TAG_AI_MUST_PLAY = AI_MUST_PLAY
        // TREASURE = DISCOVER
        // SHOWN_HERO_POWER = HERO_POWER
        // OVERKILL = 380

        // # Deleted
        // IGNORE_DAMAGE = 1
        // COPY_DEATHRATTLE_INDEX = 56
        // CARD_ID = 186
        // INCOMING_HEALING_MULTIPLIER = 233
        // INCOMING_HEALING_ADJUSTMENT = 234
        // INCOMING_HEALING_CAP = 235
        // INCOMING_DAMAGE_MULTIPLIER = 236
        // INCOMING_DAMAGE_ADJUSTMENT = 237
        // INCOMING_DAMAGE_CAP = 238
        // OUTGOING_DAMAGE_CAP = 273
        // OUTGOING_DAMAGE_ADJUSTMENT = 274
        // OUTGOING_DAMAGE_MULTIPLIER = 275
        // OUTGOING_HEALING_CAP = 276
        // OUTGOING_HEALING_ADJUSTMENT = 277
        // OUTGOING_HEALING_MULTIPLIER = 278
        // INCOMING_ABILITY_DAMAGE_ADJUSTMENT = 279
        // INCOMING_COMBAT_DAMAGE_ADJUSTMENT = 280
        // OUTGOING_ABILITY_DAMAGE_ADJUSTMENT = 281
        // OUTGOING_COMBAT_DAMAGE_ADJUSTMENT = 282
        // OUTGOING_ABILITY_DAMAGE_MULTIPLIER = 283
        // OUTGOING_ABILITY_DAMAGE_CAP = 284
        // INCOMING_ABILITY_DAMAGE_MULTIPLIER = 285
        // INCOMING_ABILITY_DAMAGE_CAP = 286
        // OUTGOING_COMBAT_DAMAGE_MULTIPLIER = 287
        // OUTGOING_COMBAT_DAMAGE_CAP = 288
        // INCOMING_COMBAT_DAMAGE_MULTIPLIER = 289
        // INCOMING_COMBAT_DAMAGE_CAP = 290
        // DIVINE_SHIELD_READY = 314
        // IGNORE_DAMAGE_OFF = 354
        // NUM_OPTIONS = 359

        // # Missing, only present in logs
        // WEAPON = 334

        // CANT_BE_EXHAUSTED = 244
        // CANT_EXHAUST = 226
        // CANT_TARGET = 228
        // CANT_DESTROY = 229
        // # Enum number changed
        // # HISTORY_PROXY_NO_BIG_CARD = 427
    }
}

enum_from_primitive! {
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub enum PlayReq {
        ReqMinionTarget = 1,
        ReqFriendlyTarget = 2,
        ReqEnemyTarget = 3,
        ReqDamagedTarget = 4,
        // REQ_ENCHANTED_TARGET = 5
        ReqFrozenTarget = 6,
        // REQ_CHARGE_TARGET = 7
        ReqTargetMaxAttack = 8,
        ReqNonSelfTarget = 9,
        ReqTargetWithRace = 10,
        ReqTargetToPlay = 11,
        // REQ_TARGET_TO_PLAY = 11
        ReqNumMinionSlots = 12,
        ReqWeaponEquipped = 13,
        // REQ_ENOUGH_MANA = 14
        // REQ_YOUR_TURN = 15
        // REQ_NONSTEALTH_ENEMY_TARGET = 16
        ReqHeroTarget = 17,
        // REQ_SECRET_CAP = 18
        // REQ_MINION_CAP_IF_TARGET_AVAILABLE = 19
        // REQ_MINION_CAP = 20
        // REQ_TARGET_ATTACKED_THIS_TURN = 21
        ReqTargetIfAvailable = 22,
        ReqMinimumEnemyMinions = 23,
        ReqTargetForCombo = 24,
        // REQ_NOT_EXHAUSTED_ACTIVATE = 25
        // REQ_UNIQUE_SECRET = 26
        // REQ_TARGET_TAUNTER = 27
        // REQ_CAN_BE_ATTACKED = 28
        // REQ_ACTION_PWR_IS_MASTER_PWR = 29
        // REQ_TARGET_MAGNET = 30
        // REQ_ATTACK_GREATER_THAN_0 = 31
        // REQ_ATTACKER_NOT_FROZEN = 32
        // REQ_HERO_OR_MINION_TARGET = 33
        // REQ_CAN_BE_TARGETED_BY_SPELLS = 34
        // REQ_SUBCARD_IS_PLAYABLE = 35
        // REQ_TARGET_FOR_NO_COMBO = 36
        // REQ_NOT_MINION_JUST_PLAYED = 37
        // REQ_NOT_EXHAUSTED_HERO_POWER = 38
        // REQ_CAN_BE_TARGETED_BY_OPPONENTS = 39
        // REQ_ATTACKER_CAN_ATTACK = 40
        ReqTargetMinAttack = 41,
        // REQ_CAN_BE_TARGETED_BY_HERO_POWERS = 42
        // REQ_ENEMY_TARGET_NOT_IMMUNE = 43
        ReqEntireEntourageNotInPlay = 44,
        ReqMinimumTotalMinions = 45,
        ReqMustTargetTaunter = 46,
        ReqUndamagedTarget = 47,
        // REQ_CAN_BE_TARGETED_BY_BATTLECRIES = 48
        ReqSteadyShot = 49,
        ReqMinionOrEnemyHero = 50,
        ReqTargetIfAvailableAndDragonInHand = 51,
        ReqLegendaryTarget = 52,
        // REQ_FRIENDLY_MINION_DIED_THIS_TURN = 53
        ReqFriendlyMinionDiedThisGame = 54,
        ReqEnemyWeaponEquipped = 55,
        ReqTargetIfAvailableAndMinimumFriendlyMinions = 56,
        // REQ_TARGET_WITH_BATTLECRY = 57
        ReqTargetWithDeathrattle = 58,
        ReqTargetIfAvailableAndMinimumFriendlySecrets = 59,
        ReqSecretCapForNonSecret = 60,
        // REQ_TARGET_EXACT_COST = 61
        ReqStealthedTarget = 62,
        ReqMinionSlotOrManaCrystalSlot = 63,
        // REQ_DRAG_TO_PLAY = 64
    }
}
